#+TITLE: Queue Kapp Todo List
#+AUTHOR: Matt Raykowski
#+EMAIL: matt.raykowski@kineticdata.com

* Implementation Notes
** Design Challenges
*** Ad-hoc Subtasks
**** How do we identify forms that are eligible for ad-hoc subtasks? What is the criteria? 
**** Where do we put the Add Subtask button/link/dropdown?
**** Where do we put the subtask embedded form when one is chosen?
*** Are we eliminating the the assignment tab?
**** When there is no assignment: _Assign_
**** When there is only a group assignment: _Base Group_ > _Middle Group_ > _Assign_
**** When there is an individual assigned: _Base Group_ > _Middle Group_ > _Person Name_
**** If show assignment as above - how do we distinguish between a group in the group hierarchy and the assigned individual?
*** Will we have multiple Queue Types within a single Kapp?
The goal is to determine whether an "HR Queue" and an "IT Queue" can be in the same Kapp. 
This is currently accomplished by spinning up several Kapps.
**** How do we choose or switch between queues?
**** How do we control who can see which queues?
This isn't just visibility - since these are just submissions a clever user could manipulate other user's data. 
***** Can we limit this in Security Policies? 
****** I don't think we can limit access to submissions based on submission values.
****** We can limit based upon form but then each "Request More Information" form needs to be duplicated for each Queue Type.

*** Filter definition improvements:
**** Left Values
The _Left Values_ represent things to be compared against. Below is a list of all of these:
***** values[FIELDNAME] - do we provide typeahead of Kapp Fields to make this easier? Similar to the lookup in the builder?
***** coreState
***** type - currently implied, may need to override if we allow multiple queue types.
***** form (slug?) - is currently used to identify the "type" of work order.
**** Right Values
Right values can be a free-form string or a macro. Below are the only macros currently defined.
***** Free-form string.
***** ${me} - implies the current user's username.
***** ${openStatuses} - implies "IN ('Open', 'In Progress')" - might not be necessary if we have IN support.
**** Operations
***** Equality
***** In
**** Timelines
***** Specify which timeline to use ('closedAt', 'createdAt', 'submittedAt', 'updatedAt')
***** Specify the sorting direction.
***** Specify an optional 'start' and 'end' date/time.
**** Support AND/OR contexts.
*** Batch Operations
John would like to be able to select a number of items from the list view which are the same type and at the same basic state and then
fill out the form and submit that form for all of the items.
**** How do we know in the list view if they're on the same page (for multi-page work orders.)
**** Do we load a single subform or build a basic client-side form which makes a direct API call?
* Features [0%]
** List View
*** *Stories*
** Details View
** TODO Assignment [0%]
*** *Stories*
*** TODO Design in-place re-assignment.
** Notes
** TODO Ad-hoc Sub-tasks [0%]
*** *Stories*
*** TODO List subtask cards on the summary view
*** TODO Add "Add Subtask" link and dropdown [0/3]
+ [ ] Retrieve list of eligible forms for subtasks
+ [ ] Implement add button and dropdown
+ [ ] Implement subtask form location


